### ISSUE TITLE
Invalid response code (403) from URL: http://jenkins-zh.gitee.io/update-center-mirror/tsinghua/update-center.json?uctest

### ISSUE THREAD

**Issue by qinhaoalg** [jenkins-zh/mirror-adapter#12]
java.net.HttpRetryException: Invalid response code (403) from URL: http://jenkins-zh.gitee.io/update-center-mirror/tsinghua/update-center.json?uctest
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.testConnection(UpdateCenter.java:1385)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.checkUpdateCenter(UpdateCenter.java:1166)
	at hudson.model.UpdateCenter$ConnectionCheckJob.run(UpdateCenter.java:1615)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)

**Comment by LinuxSuRen** [comment]
Could you please provide the context and details?
